# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: math.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='math.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\nmath.proto\",\n\nAddRequest\x12\x0e\n\x06valueA\x18\x01 \x01(\x05\x12\x0e\n\x06valueB\x18\x02 \x01(\x05\"\x1a\n\x0b\x41\x64\x64Response\x12\x0b\n\x03sum\x18\x01 \x01(\x05\"\x1c\n\x0bSqrtRequest\x12\r\n\x05value\x18\x01 \x01(\x01\"\x1d\n\x0cSqrtResponse\x12\r\n\x05value\x18\x01 \x01(\x01\"\x1c\n\x0bStatRequest\x12\r\n\x05value\x18\x01 \x01(\x05\"*\n\x0cStatResponse\x12\x0b\n\x03sum\x18\x01 \x01(\x05\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"\x1e\n\rFactorRequest\x12\r\n\x05value\x18\x01 \x01(\x05\"\x1f\n\x0e\x46\x61\x63torResponse\x12\r\n\x05value\x18\x01 \x01(\x05\x32\xa9\x01\n\x04Math\x12%\n\x04Sqrt\x12\x0c.SqrtRequest\x1a\r.SqrtResponse\"\x00\x12\"\n\x03\x41\x64\x64\x12\x0b.AddRequest\x1a\x0c.AddResponse\"\x00\x12\'\n\x04Stat\x12\x0c.StatRequest\x1a\r.StatResponse\"\x00(\x01\x12-\n\x06\x46\x61\x63tor\x12\x0e.FactorRequest\x1a\x0f.FactorResponse\"\x00\x30\x01\x62\x06proto3')
)




_ADDREQUEST = _descriptor.Descriptor(
  name='AddRequest',
  full_name='AddRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='valueA', full_name='AddRequest.valueA', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='valueB', full_name='AddRequest.valueB', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=58,
)


_ADDRESPONSE = _descriptor.Descriptor(
  name='AddResponse',
  full_name='AddResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sum', full_name='AddResponse.sum', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=86,
)


_SQRTREQUEST = _descriptor.Descriptor(
  name='SqrtRequest',
  full_name='SqrtRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='SqrtRequest.value', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=116,
)


_SQRTRESPONSE = _descriptor.Descriptor(
  name='SqrtResponse',
  full_name='SqrtResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='SqrtResponse.value', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=147,
)


_STATREQUEST = _descriptor.Descriptor(
  name='StatRequest',
  full_name='StatRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='StatRequest.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=177,
)


_STATRESPONSE = _descriptor.Descriptor(
  name='StatResponse',
  full_name='StatResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sum', full_name='StatResponse.sum', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='count', full_name='StatResponse.count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=221,
)


_FACTORREQUEST = _descriptor.Descriptor(
  name='FactorRequest',
  full_name='FactorRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='FactorRequest.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=223,
  serialized_end=253,
)


_FACTORRESPONSE = _descriptor.Descriptor(
  name='FactorResponse',
  full_name='FactorResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='FactorResponse.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=255,
  serialized_end=286,
)

DESCRIPTOR.message_types_by_name['AddRequest'] = _ADDREQUEST
DESCRIPTOR.message_types_by_name['AddResponse'] = _ADDRESPONSE
DESCRIPTOR.message_types_by_name['SqrtRequest'] = _SQRTREQUEST
DESCRIPTOR.message_types_by_name['SqrtResponse'] = _SQRTRESPONSE
DESCRIPTOR.message_types_by_name['StatRequest'] = _STATREQUEST
DESCRIPTOR.message_types_by_name['StatResponse'] = _STATRESPONSE
DESCRIPTOR.message_types_by_name['FactorRequest'] = _FACTORREQUEST
DESCRIPTOR.message_types_by_name['FactorResponse'] = _FACTORRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddRequest = _reflection.GeneratedProtocolMessageType('AddRequest', (_message.Message,), dict(
  DESCRIPTOR = _ADDREQUEST,
  __module__ = 'math_pb2'
  # @@protoc_insertion_point(class_scope:AddRequest)
  ))
_sym_db.RegisterMessage(AddRequest)

AddResponse = _reflection.GeneratedProtocolMessageType('AddResponse', (_message.Message,), dict(
  DESCRIPTOR = _ADDRESPONSE,
  __module__ = 'math_pb2'
  # @@protoc_insertion_point(class_scope:AddResponse)
  ))
_sym_db.RegisterMessage(AddResponse)

SqrtRequest = _reflection.GeneratedProtocolMessageType('SqrtRequest', (_message.Message,), dict(
  DESCRIPTOR = _SQRTREQUEST,
  __module__ = 'math_pb2'
  # @@protoc_insertion_point(class_scope:SqrtRequest)
  ))
_sym_db.RegisterMessage(SqrtRequest)

SqrtResponse = _reflection.GeneratedProtocolMessageType('SqrtResponse', (_message.Message,), dict(
  DESCRIPTOR = _SQRTRESPONSE,
  __module__ = 'math_pb2'
  # @@protoc_insertion_point(class_scope:SqrtResponse)
  ))
_sym_db.RegisterMessage(SqrtResponse)

StatRequest = _reflection.GeneratedProtocolMessageType('StatRequest', (_message.Message,), dict(
  DESCRIPTOR = _STATREQUEST,
  __module__ = 'math_pb2'
  # @@protoc_insertion_point(class_scope:StatRequest)
  ))
_sym_db.RegisterMessage(StatRequest)

StatResponse = _reflection.GeneratedProtocolMessageType('StatResponse', (_message.Message,), dict(
  DESCRIPTOR = _STATRESPONSE,
  __module__ = 'math_pb2'
  # @@protoc_insertion_point(class_scope:StatResponse)
  ))
_sym_db.RegisterMessage(StatResponse)

FactorRequest = _reflection.GeneratedProtocolMessageType('FactorRequest', (_message.Message,), dict(
  DESCRIPTOR = _FACTORREQUEST,
  __module__ = 'math_pb2'
  # @@protoc_insertion_point(class_scope:FactorRequest)
  ))
_sym_db.RegisterMessage(FactorRequest)

FactorResponse = _reflection.GeneratedProtocolMessageType('FactorResponse', (_message.Message,), dict(
  DESCRIPTOR = _FACTORRESPONSE,
  __module__ = 'math_pb2'
  # @@protoc_insertion_point(class_scope:FactorResponse)
  ))
_sym_db.RegisterMessage(FactorResponse)



_MATH = _descriptor.ServiceDescriptor(
  name='Math',
  full_name='Math',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=289,
  serialized_end=458,
  methods=[
  _descriptor.MethodDescriptor(
    name='Sqrt',
    full_name='Math.Sqrt',
    index=0,
    containing_service=None,
    input_type=_SQRTREQUEST,
    output_type=_SQRTRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Add',
    full_name='Math.Add',
    index=1,
    containing_service=None,
    input_type=_ADDREQUEST,
    output_type=_ADDRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Stat',
    full_name='Math.Stat',
    index=2,
    containing_service=None,
    input_type=_STATREQUEST,
    output_type=_STATRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Factor',
    full_name='Math.Factor',
    index=3,
    containing_service=None,
    input_type=_FACTORREQUEST,
    output_type=_FACTORRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MATH)

DESCRIPTOR.services_by_name['Math'] = _MATH

# @@protoc_insertion_point(module_scope)
